# Generated by Django 3.1.2 on 2020-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsta', '0006_auto_20201017_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
        ),
    ]
